@extends("admin.layout")

@section("title")
Assign Student Degrees
@endsection

@section("main")
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            
            <div class="card shadow-sm border-0 rounded-3 mb-4">
                <div class="card-body d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="fw-bold mb-1">AI Prompt Helper</h6>
                        <p class="text-muted small mb-0">Copy the student list and instructions to use with your PDF extractor.</p>
                    </div>
                    <button type="button" id="copy" class="btn btn-sm btn-light rounded-pill px-3 fw-bold shadow-sm">
                        <i class="fas fa-copy me-2"></i> Copy Prompt
                    </button>
                </div>
            </div>

            <div class="card shadow border-0 rounded-3 overflow-hidden">
                <div class="card-header bg-primary text-white py-3">
                    <h5 class="mb-0 fw-bold">
                        <i class="fas fa-file-import me-2"></i> Import Course Degrees
                    </h5>
                </div>
                
                <div class="card-body p-4">
                    @if ($errors->any())
                        <div class="alert alert-danger border-0 shadow-sm mb-4">
                            <ul class="mb-0 small">
                                @foreach ($errors->all() as $error)
                                    <li><i class="fas fa-exclamation-triangle me-2"></i> {{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action='{{ url("dashboard/degrees/store") }}' method="POST">
                        @csrf
                        
                        <div class="mb-4">
                            <label class="form-label fw-bold">Select Targeted Course</label>
                            <div class="input-group">
                                <span class="input-group-text bg-light text-secondary"><i class="fas fa-graduation-cap"></i></span>
                                <select name="course" class="form-select">
                                    @foreach ($courses as $course)
                                        <option value="{{ $course->id }}">{{ $course->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="mb-4">
                            <label class="form-label fw-bold">Extracted JSON Data</label>
                            <textarea name="degrees" class="form-control font-monospace text-primary bg-light" 
                                      rows="8" placeholder='{"ID": {"grade": VALUE}}'></textarea>
                            <div class="form-text text-muted small">
                                <i class="fas fa-info-circle me-1"></i> Paste the raw JSON output generated by the AI here.
                            </div>
                        </div>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary rounded-pill py-2 fs-5 fw-bold shadow-sm text-white">
                                <i class="fas fa-check-circle me-2"></i> Submit Degrees
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection
@section("script")
<script>
    // Logic remains untouched as requested
    const users = {{ Illuminate\Support\Js::from($users) }}
    let start = 'Role: Act as a Data Mapping Specialist.\n Task: Match student names from an uploaded PDF to their corresponding IDs provided in the list below, then extract their grades.\n Input 1 (User ID Mapping):'
    let end = `Input 2 (PDF Content): \n Please extract the names and grades from the attached PDF file. \n Instructions: \n Use the names in the PDF to find the corresponding ID from Input 1.\n Link the extracted grade to that specific ID. \n If a name in the PDF has a slight spelling variation but is clearly the same person, match it. \n Output Format: \n Return ONLY a raw JSON object with no conversational text or markdown blocks. The format must be exactly: \n {"ID": {"grade": VALUE}} \n Example Output: \n {"2": {"grade": 95}, "3": {"grade": 88}} \n Strict Filtering Rule: If a name exists in the PDF but does NOT have a corresponding ID in 'Input 1', IGNORE it completely. DO NOT include it in the final JSON, and do not attempt to create a dummy ID for it.`
    
    let s = "";
    users.forEach(ele => {
        s = s + `id: ${ele.id}, name: ${ele.name} \n`
    });

    $("#copy").click(function() {
        navigator.clipboard.writeText(start + "\n[" + s + "]\n" + end).then(() => {
            alert("Data copied successfully! You can now paste it into the AI Chat.");
        }).catch(err => alert("Error copying text: " + err))
    })
</script>
@endsection